version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 100
  reviewers:
  - NeroAzure
  assignees:
  - NeroAzure
