language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  include:
  - php: 7.1
    env: COMPOSER_FLAGS="--prefer-lowest"
  - php: 7.2
    env: COMPOSER_FLAGS="--prefer-lowest"
  allow_failures:
  - php: 7.4
  - php: nightly

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - vendor/bin/phpcs -s
  - vendor/bin/phpmd src,tests text phpmd.xml
