name: "Test PHP"
on: [ pull_request ]
jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php-versions: ['7.3', '7.4', '8.0']
        composer-arguments: ['--prefer-lowest', '']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, curl, zip
          coverage: xdebug
          tools: composer

      - name: Install dependencies
        run: composer update --no-interaction --no-suggest --no-progress --optimize-autoloader ${{ matrix.composer-arguments }}

      - name: Run
        run: composer run test
